### ISSUE TITLE
NAD Removal Error

### ISSUE THREAD

**Issue by EmeraldCandy** [ScorpioStation/ScorpioStation#178]
**Problem Description**:
NAD does not properly get removed from inventory

**What did you expect to happen**: 
Item should have been removed from the inventory and placed somewhere on the station Z level with flooring

**What happened instead**:
NAD spammed the message "You feel like something has disappeared" repeatedly until returning to Z level 1

**Why is this bad/What are the consequences:**
Possible z-level exploitation of NAD

**Steps to reproduce the problem**:
Insert NAD into evidence bag, then insert into a box, then proceed to move to a different Z level

**Comment by SteelSlayer** [comment]
Found the issue. It's because Emerald station doesn't have any blob start landmarks. Understandable because Scorpio/Para uses blob mice now so we don't need them. However the nuke disk looks for these to teleport to after it's qdel'd.
```js
/obj/effect/landmark/New()
    ...
    if("blobstart")
	GLOB.blobstart += loc
        qdel(src)
    ...
```
`GLOB.blobstart` is empty here:
```js
/obj/item/disk/nuclear/Destroy(force)
    ...
    if(GLOB.blobstart.len > 0)
        ...
    else
	error("[src] was supposed to be destroyed, but we were unable to locate a blobstart landmark to spawn a new one.")
```
![image](https://user-images.githubusercontent.com/42044220/90030216-6749c080-dc81-11ea-81d2-d55ea322014f.png)

**Comment by blinkdog** [comment]
I believe the same issue is causing #121

**Comment by SteelSlayer** [comment]
By the way, I kinda made a mistake in my original post by implying we don't need blobstart landmarks. It turns out blob **mice** still use these spawns.
